version: '3.7'

services:
  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/conduit
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - conduit
    depends_on:
      - app

  app:
    build:
      args:
        user: conduit
        uid: 1000
      context: .docker
    volumes:
      - .:/var/www/conduit
    networks:
      - conduit
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.3
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: conduit
      MARIADB_USER: local
      MARIADB_PASSWORD: local123
    networks:
      - conduit

networks:
  conduit: